### ISSUE TITLE
Use Quarkus cli tool to create project

### ISSUE THREAD

**Issue by kdubois** [redhat-developer-demos/quarkus-tutorial#100]
Should we use the quarkus cli to create a new project?  IMO this would be much cleaner and more agnostic (mvn vs gradle)

eg `quarkus create app -x resteasy com.redhat.developers:tutorial-app:1.0-SNAPSHOT`

instead of `mvn "io.quarkus:quarkus-maven-plugin:create" \
  -DprojectGroupId="com.redhat.developers" \
  -DprojectArtifactId="tutorial-app" \
  -DprojectVersion="1.0-SNAPSHOT" \
  -DclassName="HelloResource" \
  -Dpath="hello" \
  -Dextensions="resteasy"`

**Comment by lordofthejars** [comment]
Yes it's something that it's really cool and also with 2.15 release now, you can build and push containers from CLI. My point is that if we tell them to use quarkus CLI then they need to install another tool, while probably they already have Maven installed. Said that, I think it would be nice to 

* Add in the installation page how to install Quarkus CLI
* Add a tab of how to get the same but using the CLI

**Comment by kdubois** [comment]
Makes sense.  I'll work on a pull request
