### ISSUE TITLE
Update tutorial to Quarkus 3

### ISSUE THREAD

**Issue by kdubois** [redhat-developer-demos/quarkus-tutorial#109]
Quarkus 3 has been released.  We should update the tutorial.  

Issues that will need to be resolved:

- [x] Quarkus 3 comes with Hibernate 6 which has some breaking changes. in the import.sql we should add a line: `create sequence hibernate_sequence start with 1 increment by 1;`
- [x] Quarkus 3 is jakartaEE 10 based, we need to replace all javax with jakarta

**Comment by lordofthejars** [comment]
Could we use the `quarkus update` command to test it?

**Comment by kdubois** [comment]
That could be interesting.  Like, go through the tutorial using Quarkus 2 and then do the quarkus update and see if everything still works.  And then update the tutorial accordingly with the updated jakarta.* imports.

**Comment by kdubois** [comment]
https://github.com/redhat-developer-demos/quarkus-tutorial/pull/110
