### ISSUE TITLE
Setup instructions don't work

### ISSUE THREAD

**Issue by edeandrea** [redhat-developer-demos/quarkus-tutorial#111]
i started going through this using the "container image" approach on https://redhat-developer-demos.github.io/quarkus-tutorial/quarkus-tutorial/setup.html

The command

```
docker run -ti -p 8080:8080 -v `pwd`/work:/work \
  -v `mvn help:evaluate -Dexpression=settings.localRepository | grep \
  -v '\[INFO\]'`:/opt/developer/.m2/repository \
  --rm quay.io/rhdevelopers/tutorial-tools:0.0.4 bash
```

doesn't work.

```
╰─ docker run -ti -p 8080:8080 -v `pwd`/work:/work \
  -v `mvn help:evaluate -Dexpression=settings.localRepository | grep \
  -v '\[INFO\]'`:/opt/developer/.m2/repository \
  --rm quay.io/rhdevelopers/tutorial-tools:0.0.4 bash
Unable to find image 'from:latest' locally
docker: Error response from daemon: pull access denied for from, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```

I _think_ that the image should be `quay.io/rhdevelopers/tutorial-tools:0.0.6`, not version `0.0.4`, but when I use `0.0.6`, it fails too with a different error:

```
╰─ docker run -ti -p 8080:8080 -v `pwd`/work:/work \
  -v `mvn help:evaluate -Dexpression=settings.localRepository | grep \
  -v '\[INFO\]'`:/opt/developer/.m2/repository \
  --rm quay.io/rhdevelopers/tutorial-tools:0.0.6 bash
docker: invalid reference format: repository name must be lowercase.
See 'docker run --help'.
```

**Comment by kdubois** [comment]
https://github.com/redhat-developer-demos/quarkus-maven-repo-cachier/pull/3

**Comment by edeandrea** [comment]
I'm not sure how it would be any different? The image hasn't been updated.

```
╰─ docker pull quay.io/rhdevelopers/tutorial-tools:0.0.6
0.0.6: Pulling from rhdevelopers/tutorial-tools
Digest: sha256:01ce2c6306d9885072933af6f74993ec97fe61926416076e5c6b9dcd5c588a74
Status: Image is up to date for quay.io/rhdevelopers/tutorial-tools:0.0.6
quay.io/rhdevelopers/tutorial-tools:0.0.6
```

![image](https://github.com/redhat-developer-demos/quarkus-tutorial/assets/363447/ff61f754-0299-486d-bc9a-a095d2c6e4d6)

**Comment by kdubois** [comment]
the image version of that repo isn't the problem ..  :)

**Comment by edeandrea** [comment]
I don't understand then. If the image hasn't been updated with a newer version then how do you expect it to now work?

**Comment by edeandrea** [comment]
Nothing has changed...

```
╰─ docker run -ti -p 8080:8080 -v `pwd`/work:/work \
  -v `mvn help:evaluate -Dexpression=settings.localRepository | grep \
  -v '\[INFO\]'`:/opt/developer/.m2/repository \
  --rm quay.io/rhdevelopers/tutorial-tools:0.0.6 bash
docker: invalid reference format: repository name must be lowercase.
See 'docker run --help'.
```

**Comment by kdubois** [comment]
Is this VSCode that's reporting the docker run command? Where is that coming from?

**Comment by edeandrea** [comment]
Not VSCode - just a terminal

From https://redhat-developer-demos.github.io/quarkus-tutorial/quarkus-tutorial/setup.html#_cli_tools

![image](https://github.com/redhat-developer-demos/quarkus-tutorial/assets/363447/a6b86852-b903-4c83-8b26-5bdd5bbcfc94)

**Comment by kdubois** [comment]
oh I see... I was just opening the tutorial in vscode and then it suggests to use the container and it works.   So looks like I need to update this command in the tutorial.  Thanks for catching that :D

**Comment by edeandrea** [comment]
I don't use VSCode - ever :) So I was just following along with the tutorial playing dumb :)

**Comment by edeandrea** [comment]
And also the instructions should be updated. The first command says to `docker pull` version `0.0.6`, yet the `docker run` command shows `0.0.4`. Whatever the right version is, they should probably match :)

**Comment by kdubois** [comment]
The issue was the output of the maven command which now shows plugin validation warnings.  The command looking for the maven repo path was filtering out info but not warning.  This wasn't foreseen by the person creating this command :).  Just pushed a fix for both the version not matching up and filtering out warnings from the maven command

**Comment by edeandrea** [comment]
What? No multi-arch images? :)

```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```

**Comment by kdubois** [comment]
Let's create a separate issue for that :)
