### ISSUE TITLE
Native build windows requires extra maven tag

### ISSUE THREAD

**Issue by kad-zuuret** [redhat-developer-demos/quarkus-tutorial#123]
Building a native image on windows requires an additional maven tag. 
This is not described in the [tutorial](https://redhat-developer-demos.github.io/quarkus-tutorial/quarkus-tutorial/basics.html#_build_and_run_the_quarkus_application)

./mvn install -Dnative -DskipTests **-Dquarkus.native.container-build=true**

**Comment by kdubois** [comment]
Thank you!

**Comment by kdubois** [comment]
done
