### ISSUE TITLE
Incomplete sentence in reactive section

### ISSUE THREAD

**Issue by gsmet** [redhat-developer-demos/quarkus-tutorial#154]
Not sure what you wanted to write here: https://redhat-developer-demos.github.io/quarkus-tutorial/quarkus-tutorial/14_reactive.html but the sentence starting with `to online beer database` is incomplete.

**Comment by kdubois** [comment]
fixed in this commit : https://github.com/redhat-developer-demos/quarkus-tutorial/commit/f7de6dab4266d46f6119dfb4df27af7e62f6ed31
