### ISSUE TITLE
Inconsistent project for reactive section

### ISSUE THREAD

**Issue by gsmet** [redhat-developer-demos/quarkus-tutorial#155]
In https://redhat-developer-demos.github.io/quarkus-tutorial/quarkus-tutorial/14_reactive.html, the user is encouraged to create a new project from scratch but then we tell them to get to the root of the old project that was created initially:

> Then open a new terminal window, and make sure you’re at the root of your tutorial-app project, then run:

This sounds odd?

**Comment by gsmet** [comment]
Also given until now, we created the projects with the CLI, maybe it's better to be consistent and also enforce the name of this new project?

**Comment by gsmet** [comment]
Another issue: we don't tell the user to start the project in dev mode before requesting it.

**Comment by cescoffier** [comment]
@gsmet Great... I don't know anything about this workshop.

**Comment by kdubois** [comment]
Fixed (as much as possible) in https://github.com/redhat-developer-demos/quarkus-tutorial/pull/163  

The punkapi service has been permanently removed. I found the source code and added instructions to deploy it on an Openshift Sandbox.. not ideal but for now this should work.  We may want to consider porting it over to Quarkus and adding it as part of the basic tutorial to deploy or something.
