### ISSUE TITLE
Missing instructions for chapter 5

### ISSUE THREAD

**Issue by dadoonet** [redhat-developer-demos/quarkus-tutorial#2]
In https://quarkus-workshop.devx.red/quarkus-tutorial/0.15.0/05-quarkus-panache.html#quarkusp-access-db you wrote:

> To be able to access maridb database locally, you need to `port-forward` the remote port to local port.
> 
> Open a new terminal window and run the following command:
> 
> You can now use `adminer` or any other SQL tool to access the mariadb using the `<your ip address>:3306`

But there is no command here.

**Comment by dadoonet** [comment]
While you are at it, replace all `maridb`, `mariab` typos by `mariadb` :)

**Comment by kameshsampath** [comment]
fixed!
