### ISSUE TITLE
Making quarkus version as env variable

### ISSUE THREAD

**Issue by kameshsampath** [redhat-developer-demos/quarkus-tutorial#28]
Making Quarkus version as environment variable, as that helps in the commands like to be easy to maintain during release updates:

```
mvn io.quarkus:quarkus-maven-plugin:$QUARKUS_VERSION:create \
  -DprojectGroupId="com.example" \
  -DprojectArtifactId="fruits-app" \
  -DprojectVersion="1.0-SNAPSHOT" \
  -DclassName="FruitResource" \
  -Dpath="fruit"```

**Comment by kdubois** [comment]
closing since we've removed the version number altogether (just going with the latest stable version by default)
