### ISSUE TITLE
Remove `-n quarkustutorial` in chapter 5

### ISSUE THREAD

**Issue by dadoonet** [redhat-developer-demos/quarkus-tutorial#3]
In chapter 5 you are using:

```
oc apply -n quarkustutorial -f $TUTORIAL_HOME/kubernetes-apps/mariadb.yaml
```

Because we set the name already in chapter 1, this could be simplified and would work then with project names like `quarkustutorial-xx` as well.

```
oc apply -f $TUTORIAL_HOME/kubernetes-apps/mariadb.yaml
```

I'd just remove `-n quarkustutorial` everywhere in this page.

**Comment by kameshsampath** [comment]
@dadoonet - as discussed during the session the name changes as per the setting either DIY or workshop. the workshop default one is `quarkustutorial`. But will still check to see the consistency
