### ISSUE TITLE
Can not access to Adminer

### ISSUE THREAD

**Issue by dadoonet** [redhat-developer-demos/quarkus-tutorial#4]
In https://quarkus-workshop.devx.red/quarkus-tutorial/0.15.0/05-quarkus-panache.html#quarkus-fruit-app-db we are supposed to access to Adminer console and log in.

But I'm getting this error when doing that:

```
SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name does not resolve
```

![image](https://user-images.githubusercontent.com/274222/58608600-fb2aa900-82d6-11e9-8a99-ee873be5f08c.png)

**Comment by kameshsampath** [comment]
@dadoonet  - you need to use the kubernetes service name like `mariadb` or `ip:port`, I will add that to the instruction.
