### ISSUE TITLE
Adding Workshop Site

### ISSUE THREAD

**Issue by kameshsampath** [redhat-developer-demos/quarkus-tutorial#42]
Add workshop site that can be used to generate documentation for workshop 

- it should have a property called `workshop` to do conditionals
- no kubernetes for workshops
- add a workshop only page that shows docker pull commands to download all common images 
- workshop only navigation

**Comment by lordofthejars** [comment]
@kameshsampath I think the property instead of called `workshop` I'll call it `kubernetes` since this is what we want to avoid. In this way, if we ever want to do a workshop and use Kubernetes, then the property name will have more sense.

**Comment by kameshsampath** [comment]
@lordofthejars  - the workshop stuff is generic, may tomorrow we might want to run with `kubernetes` so its better to be workshop and consistent across all our tutorials. OK?

**Comment by lordofthejars** [comment]
ok
