### ISSUE TITLE
Duplicate entry "Build and run Application locally"

### ISSUE THREAD

**Issue by MarkusTiede** [redhat-developer-demos/quarkus-tutorial#45]
https://eclipsecon-quarkus-lab.web.app/quarkus-tutorial/0.24.0/index.html

![Bildschirmfoto 2019-10-22 um 09 07 41](https://user-images.githubusercontent.com/1764012/67264535-9e10d900-f4ab-11e9-8b5c-088eb6e6b67c.png)

**Comment by lordofthejars** [comment]
Thank you very much fixed upstream and now fixing in the workshop repo.
