### ISSUE TITLE
Directory mapping via docker for `tools-container` has mixed success

### ISSUE THREAD

**Issue by emmanuelbernard** [redhat-developer-demos/quarkus-tutorial#56]
This magic command to map both `work` and `.m2/repository` between host and container actually fails mostly on Windows. 30% sucess or so. So we need a backup plan.

Also I made typos to the image proposal

Fix for typos:

```
docker run -ti -p 8080:8080 -v `pwd`/work:/work \
  -v `mvn help:evaluate -Dexpression=settings.localRepository | grep '\[INFO\]'`:/opt/developer /.m2/repository \
  --rm quay.io/rhdevelopers/tutorial-tools:0.0.3 bash
```

Simpler version that works on Windows some time

```
docker run  -p 8080:8080 -v "C:\where ever\work":/work \
  -v "C:\Users\Emmanuel Bernard\.m2\repository":/opt/developer/.m2/repository \
  --rm quay.io/rhdevelopers/tutorial-tools:0.0.3 bash
```

But offer a fallback "stateless" version

```
docker run  -p 8080:8080 \
  --rm quay.io/rhdevelopers/tutorial-tools:0.0.3 bash
```

Which requires to use vi to edit files :/ and a lot of quarkus:dev ctrl+c so not idea either.

**Comment by sebastienblanc** [comment]
Since this turned into a tutorial rather than a workshop, I think this issue is outdated.
