### ISSUE TITLE
Consider offering a container free start for the lab

### ISSUE THREAD

**Issue by emmanuelbernard** [redhat-developer-demos/quarkus-tutorial#57]
Most of people had trouble with Docker and then some.
When they did not they got very confused by the docker port and directory mapping and though Quarkus requires GraalVM.

I recommend we start the lab entirely docker free or at least optional.
And the lab instruction should be crystal clear on what step is runnable without docker and without minikube.
Maybe with foldable sections

**Comment by lordofthejars** [comment]
The truth is that in workshops we usually create a special site with
workshop=true flag which skips all kubernetes/openshift thing and just
assumes Docker. But you know that this time we couldn't make it. But in the
site with this flag enabled, the list of requirements is there and the only
mandatory docker container is MySQL. But probably we need to work a bit
more on this to make it entirely docker free.

Missatge de Emmanuel Bernard <notifications@github.com> del dia dl., 4 de
nov. 2019 a les 17:52:
