### ISSUE TITLE
Reactive docs broken - BeerService code does not generate properly

### ISSUE THREAD

**Issue by jclingan** [redhat-developer-demos/quarkus-tutorial#65]
The BeerService source code looks to be formatted properly in [06-quarkus-reactive.adoc](https://github.com/redhat-developer-demos/quarkus-tutorial/blob/master/documentation/modules/ROOT/pages/06-quarkus-reactive.adoc), but is not generated properly in the [generated tutorial](https://redhat-developer-demos.github.io/quarkus-tutorial/quarkus-tutorial/1.0.1.Final/06-quarkus-reactive.html#quarkusrpb-demo-overview). The issue seems  to be the parenthesis:

Specifically missing is:
* () -> 1
* beers.isEmpty()

**Comment by yanaga** [comment]
@lordofthejars, it seems that antora does not render the code correctly when you use the "<n>" markers inside the code.

Do you any fix or workaround for this? Or else we can just replace the "<n>" with "//n" comments and convert the instructions to a regular numbered list.

**Comment by lordofthejars** [comment]
I was thinking the same need to look closely
